# Generated by Django 5.2.7 on 2026-03-11 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etudiant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='etudiant',
            name='resident',
            field=models.CharField(choices=[('oui', 'Oui'), ('nom', 'Non')], default=111, max_length=3),
            preserve_default=False,
        ),
    ]
