# Generated by Django 5.2.7 on 2026-03-12 23:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etudiant', '0002_etudiant_resident'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chambre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=10)),
                ('site', models.CharField(choices=[('F', 'Site Filles'), ('G', 'Site Garçons')], max_length=1)),
                ('capacite', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='etudiant',
            name='chambre',
            field=models.ForeignKey(default=11, on_delete=django.db.models.deletion.CASCADE, related_name='etudiants', to='etudiant.chambre'),
            preserve_default=False,
        ),
    ]
