# Generated by Django 6.0.2 on 2026-03-14 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('etudiant', '0003_chambre_etudiant_chambre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='etudiant',
            name='identifiant_permanent',
        ),
    ]
