# Generated by Django 6.0.2 on 2026-03-15 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etudiant', '0004_remove_etudiant_identifiant_permanent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chambre',
            name='site',
        ),
        migrations.AddField(
            model_name='chambre',
            name='cite',
            field=models.CharField(choices=[('F', 'Cite Filles'), ('G', 'Cite Garçons')], default=12, max_length=1),
            preserve_default=False,
        ),
    ]
