# Generated by Django 6.0.2 on 2026-03-15 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('etudiant', '0005_remove_chambre_site_chambre_cite'),
    ]

    operations = [
        migrations.RenameField(
            model_name='anneeacademique',
            old_name='annee_debut',
            new_name='annee_academique',
        ),
        migrations.RemoveField(
            model_name='anneeacademique',
            name='annee_fin',
        ),
    ]
