# Generated by Django 6.0.2 on 2026-03-15 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etudiant', '0006_rename_annee_debut_anneeacademique_annee_academique_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anneeacademique',
            name='annee_academique',
            field=models.CharField(),
        ),
    ]
