# Generated by Django 5.2.7 on 2026-03-19 09:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etudiant', '0007_alter_anneeacademique_annee_academique'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chambre',
            old_name='numero',
            new_name='nom',
        ),
        migrations.AlterField(
            model_name='anneeacademique',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='etudiant',
            name='resident',
            field=models.CharField(choices=[('oui', 'Oui'), ('non', 'Non')], max_length=3),
        ),
        migrations.AlterField(
            model_name='filiere',
            name='annee_academique',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='etudiant.anneeacademique'),
        ),
    ]
