# Generated by Django 6.0.2 on 2026-04-17 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etudiant', '0008_rename_numero_chambre_nom_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='etudiant',
            name='chambre',
        ),
        migrations.RenameField(
            model_name='etudiant',
            old_name='resident',
            new_name='admissible',
        ),
        migrations.RemoveField(
            model_name='etudiant',
            name='actif',
        ),
        migrations.RemoveField(
            model_name='etudiant',
            name='numero_urgence',
        ),
        migrations.AddField(
            model_name='etudiant',
            name='identifiant_permanent',
            field=models.CharField(default=1111, max_length=100),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Chambre',
        ),
    ]
