# Generated by Django 6.0.2 on 2026-04-17 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etudiant', '0009_remove_etudiant_chambre_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etudiant',
            name='admissible',
            field=models.CharField(choices=[('oui', 'Oui'), ('non', 'Non')], default='non', max_length=3),
        ),
    ]
